# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2020, Intel Corporation

#
# Dockerfile - a 'recipe' for Docker to build an image of environment 
#              prepared for running libpmemobj-cpp tests.
#

# Pull base image
FROM archlinux/base:latest
MAINTAINER szymon.romik@intel.com

# Update the Apt cache and install basic tools
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm \
	asciidoc \
	autoconf \
	automake \
	bash-completion \
	clang \
	cmake \
	doxygen \
	file \
	gcc \
	gdb \
	git \
	graphviz \
	sfml \
	intel-tbb \
	libunwind \
	llvm \
	make \
	pandoc \
	perl-text-diff \
	pkg-config \
	ruby \
	sudo \
	wget \
	which \
	whois \
	xmlto

# Install libndctl
COPY install-libndctl.sh install-libndctl.sh
RUN ./install-libndctl.sh archlinux-base

# Install valgrind
COPY install-valgrind.sh install-valgrind.sh
RUN ./install-valgrind.sh

# Install pmdk
COPY install-pmdk.sh install-pmdk.sh
RUN ./install-pmdk.sh

# Add user
ENV USER user
ENV USERPASS p1a2s3s4
ENV PFILE ./password
RUN useradd -m $USER
RUN echo $USERPASS > $PFILE
RUN echo $USERPASS >> $PFILE
RUN passwd $USER < $PFILE
RUN rm -f $PFILE
RUN sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers
RUN gpasswd wheel -a $USER
USER $USER

# Clean the cache of packages
RUN rm -rf /var/cache/pacman/pkg/*

# Set required environment variables
ENV OS archlinux-base
ENV OS_VER latest
ENV PACKAGE_MANAGER pacman
ENV NOTTY 1
